class MainLocators:
    # Main page
    ACTUAL_REGION = 'ru.leroymerlin.mobile:id/tv_region'
    INFO_BUTTON = 'ru.leroymerlin.mobile:id/action_info'
    TITLE_DELIVERY = 'ru.leroymerlin.mobile:id/delivery_txt'
    BACK_BUTTON = 'android.widget.ImageButton'
    MAIN_PAGE_TITLE = '//android.widget.TextView[@text="Леруа Мерлен"]'
    LIMITED_OFFER_BUTTON = '//android.widget.TextView[@text="Смотреть все"]'
    PRODUCT_1_TILE = '//android.widget.FrameLayout[@index="1"]/android.widget.LinearLayout[@index="1"]'
    PRODUCT_1_NAME = '//android.widget.LinearLayout[@index="1"]/android.widget.RelativeLayout[@index="1"]/android.widget.TextView[@index="0"]'
    PRODUCT_2_TILE = '//android.widget.FrameLayout[@index="2"]/android.widget.LinearLayout[@index="1"]'
    PRODUCT_2_NAME = '//android.widget.FrameLayout[@index="2"]/android.widget.LinearLayout[@index="1"]/android.widget.RelativeLayout[@index="1"]/android.widget.TextView[@index="0"]'
    PRODUCT_3_NAME = '//android.widget.FrameLayout[@index="3"]/android.widget.LinearLayout[@index="1"]/android.widget.RelativeLayout[@index="1"]/android.widget.TextView[@index="0"]'
    BP_LOOK_ALL_BUTTON = '//android.widget.LinearLayout[@index="9"]/android.widget.TextView[@text="Смотреть все" and @index="0"]'
    CART_BUTTON = 'ru.leroymerlin.mobile:id/iv_basket'
    HOME_PAGE_BUTTON = 'android.widget.TextView[@text="Главный"]'
    SHOPPING_LIST_BUTTON = 'ru.leroymerlin.mobile:id/tab_shopping_list'
    PROFILE_BUTTON = '//android.widget.TextView[@text="Профиль"]'
    MY_REGION = 'ru.leroymerlin.mobile:id/tv_region'
